# See https://pre-commit.com for more information on pre-commit and its configuration

repos:
  # these hooks are from the output of `pre-commit sample-config`.
  # keeping as they are sane defaults.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

    # Python auto-formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

    # Python linting
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--extend-ignore=E203", "--max-line-length=88"]

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
      - id: reorder-python-imports
        args: ["--application-directories", "be"]

    # Javascript auto-formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

    # Javascript linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.13.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        #additional_dependencies:
        #-   react-app
