version: "3.9"
services:
  be:
    build:
      context: ..
      dockerfile: ./docker/dev.be.Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ../be/:/code
    stdin_open: true
    tty: true

  fe:
    build:
      context: ..
      dockerfile: ./docker/dev.fe.Dockerfile
    volumes:
      - ../fe/src:/app/src
      - ../fe/public:/app/public

    stdin_open: true

  nginx:
    build:
      context: ..
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - "80:80"

    # do not launch nginx until be and fe is set up for networking
    # otherwise, nginx will run faster, and error out because
    # it can't resolve the be/fe name in nginx.default.conf
    depends_on:
      - be
      - fe

  redis:
    image: "redis:alpine"
    ports:
      - 127.0.0.1:6379:6379
