version: "3.9"
services:
  be:
    build:
      context: ..
      dockerfile: ./docker/dev.be.Dockerfile
    volumes:
      - ../be/:/code
    stdin_open: true
    tty: true

  fe:
    build:
      context: ..
      dockerfile: ./docker/dev.fe.Dockerfile
    volumes:
      - /app/node_modules
      - ../fe:/app

    stdin_open: true

  nginx:
    build:
      context: ..
      dockerfile: ./docker/dev.nginx.Dockerfile
    ports:
      - "3000:80"

    # do not launch nginx until be and fe is set up for networking
    # otherwise, nginx will run faster, and error out because
    # it can't resolve the be/fe name in nginx.default.conf
    depends_on:
      - be
      - fe

  redis:
    image: "redis:alpine"
    ports:
      - 127.0.0.1:6379:6379
