version: "3.9"
services:
  be:
    build:
      context: ..
      dockerfile: ./docker/dev.be.Dockerfile
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ../be/:/code
    stdin_open: true # docker run -i
    tty: true # docker run -t

  fe:
    build:
      context: ..
      dockerfile: ./docker/dev.fe.Dockerfile
    ports:
      - 127.0.0.1:3000:3000
      # this works on the command line:
      # docker run -it --mount type=bind,source="$(pwd)"/fe,target=/app -p 3000:3000 dev.fe
      # make it into the following syntax, and then try denying the node_modules
      # :)
    volumes:
      - /app/node_modules
      - ../fe:/app

    stdin_open: true # docker run -i
    #tty: true # docker run -t

  redis:
    image: "redis:alpine"
